<a href="https://colab.research.google.com/github/yasawinidasari02/python-git-project/blob/main/data_preprocessing_template.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#step-1--- we have to import data from csv file
!pip install pandas

In [ ]:
import pandas as pd
data=pd.read_csv('Data.csv') # reads the data in the csv file

In [ ]:
data

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
data.columns

NameError: ignored

In [ ]:
data['Country']

0     France
1      Spain
2    Germany
3      Spain
4    Germany
5     France
6      Spain
7     France
8    Germany
9     France
Name: Country, dtype: object

In [ ]:
data['Country'][0]

'France'

In [ ]:
data['Age'][5]

35.0

In [ ]:
data.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [ ]:
data.head(3)

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No

In [ ]:
data.tail()

NameError: ignored

In [ ]:
#step-2---- we have to separate all the input(independent) variables and output(dependent) variables

#Y=f(X)

#independent variables---country,age,salary
X=data.iloc[:,0:-1].values

In [ ]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [ ]:
# Dependent variables--purchase
Y=data.iloc[:,-1].values

In [ ]:
print(Y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [ ]:
#step3--to fill missed values
#frequency method in categorial coloumns
#mean method in numeric data

!pip install sklearn

In [ ]:
#missing data in X
#missing data is noted with NAN
from sklearn .impute import SimpleImputer
import numpy as np

imputer=SimpleImputer(missing_values=np.nan,strategy='mean') 

imputer.fit(X[:,1:3])  # identification
X[:,1:3]=imputer.transform(X[:,1:3])


In [ ]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [ ]:
#step4--- string data have to e convertd into numerical data
#taking care of string data
#encoding the independent variables

#independent variable at index 0

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
X=ct.fit_transform(X)

In [ ]:
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, nan],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, nan, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [ ]:
# encode the dependent variables
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
Y=le.fit_transform(Y)

In [ ]:
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [ ]:
#step-5--- Feature Scaling

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X[:,3:5]=sc.fit_transform(X[:,3:5])

In [ ]:
X

array([[1.0, 0.0, 0.0, 0.7199314321591973, 0.711012758872281],
       [0.0, 0.0, 1.0, -1.6236751448696793, -1.3643758345927564],
       [0.0, 1.0, 0.0, -1.2100975136292893, -0.845528686226497],
       [0.0, 0.0, 1.0, -0.1072238303215827, -0.24020701313252774],
       [0.0, 1.0, 0.0, 0.16849459050534396, nan],
       [1.0, 0.0, 0.0, -0.5208014615619727, -0.4996305873156574],
       [0.0, 0.0, 1.0, nan, -1.0184777356819168],
       [1.0, 0.0, 0.0, 1.2713682738130507, 1.3163344319662502],
       [0.0, 1.0, 0.0, 1.5470866946399773, 1.6622325308770898],
       [1.0, 0.0, 0.0, -0.24508304073504605, 0.2786401352337316]],
      dtype=object)

In [ ]:
#step-6--- spliting the data into train and test
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [ ]:
X_train

array([[0.0, 1.0, 0.0, 0.16849459050534396, nan],
       [0.0, 0.0, 1.0, nan, -1.0184777356819168],
       [1.0, 0.0, 0.0, -0.24508304073504605, 0.2786401352337316],
       [1.0, 0.0, 0.0, 1.2713682738130507, 1.3163344319662502],
       [0.0, 1.0, 0.0, -1.2100975136292893, -0.845528686226497],
       [0.0, 0.0, 1.0, -1.6236751448696793, -1.3643758345927564],
       [1.0, 0.0, 0.0, -0.5208014615619727, -0.4996305873156574],
       [0.0, 0.0, 1.0, -0.1072238303215827, -0.24020701313252774]],
      dtype=object)

In [ ]:
X_test

array([[1.0, 0.0, 0.0, 0.7199314321591973, 0.711012758872281],
       [0.0, 1.0, 0.0, 1.5470866946399773, 1.6622325308770898]],
      dtype=object)

In [ ]:
Y_train

array([1, 0, 1, 1, 0, 1, 1, 0])

In [ ]:
Y_test

array([0, 0])